### Constants
@host = 192.168.0.3
@port = 8111
@user= admin
@password = admin
@username = test_nGlkkRNTER

### Hardcoded test data
@projectId = test_project_1
@buildTypeId = test_build_type_1

### Get roles
# @no-cookie-jar
GET http://admin:admin@{{host}}:{{port}}/app/rest/roles
Accept: application/json
Authorization: Basic test_wXRrTwXouv test_HPVkYfRVnS

### Get user
# @no-cookie-jar
GET http://admin:admin@{{host}}:{{port}}/app/rest/users/username:test_uNWSRMAGgC
Content-Type: application/json
Accept: application/json
Authorization: Basic test_uNWSRMAGgC test_DPjlNSlLnB

### Set role with user
# @no-cookie-jar
PUT http://admin:admin@{{host}}:{{port}}/app/rest/users/id:139
Content-Type: application/json
Accept: application/json
//Authorization: Basic test_wXRrTwXouv test_HPVkYfRVnS

{
  "id": "70",
  "username": "test_nGlkkRNTER",
	"role": [
		{
			"roleId": "SYSTEM_ADMIN",
			"scope": "p"
		}
	]
}

### Get token CSRF-token
# @no-cookie-jar
GET http://admin:admin@192.168.0.5:8111/login.html

### Generate CSRF-token
GET http://192.168.0.5:8111/app/rest/buildTypes/id%3ATestHNCxiHVgmT_TestOZecxfMAfC
# @no-cookie-jar
Accept: application/json
Content-Type: application/json
Authorization: Basic test_wXRrTwXouv test_HPVkYfRVnS

### 1. Create project
# @no-cookie-jar
POST http://{{user}}:{{password}}@{{host}}:{{port}}/app/rest/projects
Content-Type: application/json
Accept: application/json

{
  "parentProject": {
    "locator": "_Root"
  },
  "name": "{{projectId}}",
  "id": "{{projectId}}",
  "copyAllAssociatedSettings": true
}

### 2. Create build configuration
# @no-cookie-jar
POST http://{{user}}:{{password}}@{{host}}:{{port}}/app/rest/buildTypes
Content-Type: application/json
Accept: application/json

{
  "id": "{{buildTypeId}}",
  "name": "Print hello world",
  "project": {
    "id": "{{projectId}}"
  },
  "steps": {
    "step": [
      {
        "name": "Print hello world",
        "type": "simpleRunner",
        "properties": {
          "property": [
            {
              "name": "script.content",
              "value": "echo 'Hello World!'"
            },
            {
              "name": "teamcity.step.mode",
              "value": "default"
            },
            {
              "name": "use.custom.script",
              "value": "true"
            }
          ]
        }
      }
    ]
  }
}

### 3. Run build
# @no-cookie-jar
POST http://{{user}}:{{password}}@{{host}}:{{port}}/app/rest/buildQueue
Content-Type: application/json
Accept: application/json

{
  "buildType": {
    "id": "{{buildTypeId}}"
  }
}

### 4. Check build status
# @no-cookie-jar
GET http://{{host}}:{{port}}/app/rest/builds/id:1
Content-Type: application/json
Authorization: Basic admin admin //X-TC-CSRF-Token: 74d89213-bc74-472d-95e7-dbd6606df3b5
Accept: application/json

### 5. Generate CSRF-token
# @no-cookie-jar
GET http://@{{host}}:{{port}}/app/rest/swagger.json
Accept: application/json
Authorization: Basic admin admin



### Get any agents
# @no-cookie-jar
GET http://{{host}}:{{port}}/app/rest/agents?locator=authorized:any
Accept: application/json
Authorization: Basic test_baagyaeint 1234qwer

### Auth agent by id
# @no-cookie-jar
PUT http://{{host}}:{{port}}/httpAuth/app/rest/agents/id:11/authorizedInfo
Accept: application/json
Content-Type: application/json
Authorization: Basic test_baagyaeint 1234qwer

{
  "status": true
}



### 1. Create project
# @no-cookie-jar
POST http://{{host}}:{{port}}/app/rest/projects
Content-Type: application/json
Accept: application/json
Authorization: Basic test_baagyaeint 1234qwer

{
  "parentProject": {
    "locator": "_Root"
  },
  "name": "test_build_queue",
  "id": "test_id_12"
}


### 2. Create build type
# @no-cookie-jar
POST http://{{host}}:{{port}}/app/rest/buildTypes
Accept: application/json
Content-Type: application/json
Authorization: Basic test_baagyaeint 1234qwer

{
  "id": "test_buildTypes123",
  "name": "Print hello world",
  "project": {
    "id": "test_id_12"
  },
  "steps": {
    "step": [
      {
        "name": "Print hello world",
        "type": "simpleRunner",
        "properties": {
          "property": [
            {
              "name": "script.content",
              "value": "echo 'Hello World!'"
            },
            {
              "name": "teamcity.step.mode",
              "value": "default"
            },
            {
              "name": "use.custom.script",
              "value": "true"
            }
          ]
        }
      }
    ]
  }
}



### 3. Add build to queue
# @no-cookie-jar
POST http://{{host}}:{{port}}/app/rest/buildQueue
Accept: application/json
Content-Type: application/json
Authorization: Basic test_baagyaeint 1234qwer

{
  "buildType": {
    "id": "test_buildTypes123",
    "name": "Print hello world",
    "project": {
      "id": "test_id_12",
      "name": "test_build_queue"
    },
    "steps": {
      "step": [
        {
          "name": "Print hello world",
          "type": "simpleRunner",
          "properties": {
            "property": [
              {
                "name": "script.content",
                "value": "echo 'Hello World!'"
              },
              {
                "name": "teamcity.step.mode",
                "value": "default"
              },
              {
                "name": "use.custom.script",
                "value": "true"
              }
            ]
          }
        }
      ]
    }
  }
}



