name: Deploy to prod

on: workflow_call

# Это лишь примерные степы, как может выглядеть пайплайн деплоя на прод
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to backend to prod
        run: echo Deploy backend

  deploy-stage:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Deploy frontend to prod
        run: echo Deploy frontend